# Site wide configuration 

title: "Tzar Radio"
description: "Radio En Construcción"
#if you modify locale please have a look at _data/messages.yml too
locale: en
#for meta name="author" :
author: Andrés Montenegro

#Target date in UTC / GMT
countdown:
  theme: black
  year: 2018
  month: 7
  day: 6
  hour: 15
  minute: 20

# Site owner
owner:
  name: Andrés Montenegro
  email: andresmontenegro@programmer.net
  twitter: TzarRadio
  google-plus: 
  instagram:
  #Aboutlink = German "Impressum", provide url and caption (eg "Impressum")
  aboutlink:
    url:
    caption:


# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
